language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - mongodb
install:
  - npm install
script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls